### PR TITLE
allowing higher versions of openpyxl (needed if using Pandas 1.3.4 an…

### PR DESCRIPTION
**Pull request by proccaserra**
…d higher) and solve a dependency conflict in the isa-api

### CODE REVIEW

**Comment by althonos** [comment]
I need to update the CI before merging, since Travis-CI doesn't work anymore I'll setup GitHub Actions instead.

**Comment by althonos** [comment]
Okay this took longer than expected, but a new release is on the way :smile:

**Comment by Tomnl** [comment]
Thanks @althonos !

**Comment by proccaserra** [comment]
Sweet! Xmas comes early this year :)  
thx @althonos  & @Tomnl

**Pull request merged**
