### PR TITLE
Merging changes from Martin's (althonos) repo to Tom's (tomnl)

### PR DESCRIPTION
**Pull request by Tomnl**
My mzml2isa repo is now quite far out of date but is still referenced in search engines. To avoid confusion I am updating the repo with the most recent changes from Martin. 

I will then transfer ownership to ISA-Tools. The development of the tool will then continue at ISA-Tools/mzml2isa.  See issue 1.

### CODE REVIEW

**Comment by althonos** [comment]
Psssst @Tomnl, could you add me as a contributor now that you're omnipotent ? :smile:

**Comment by Tomnl** [comment]
Alas, I am no longer omnipotent. My admin rights were only temporary.  

Please could someone from ISA-tools (@djcomlab @proccaserra, @agbeltran) add the mzml2isa repo to the [mzml2isa-galaxy team](https://github.com/orgs/ISA-tools/teams/mzml2isa-galaxy) and then change the team name to 'xml2isa'.

I think we will be sorted after that.

**Comment by agbeltran** [comment]
I have added the mzml2isa repository to the team and changed the name.

**Comment by althonos** [comment]
Great ! Thanks Alejandra !

**Comment by Tomnl** [comment]
Thanks :+1:

**Comment by althonos** [comment]
May I also have write access to ISA-Tools/mzml2isa ? Or do you want me to continue developing on my fork, submitting occassional patches through pull requests ?

**Comment by Tomnl** [comment]
Sorry I forgot to ask for admin access.

@agbeltran : Sorry to be a pain but could you change the settings for the repo xml2isa to be admin. e.g. like the mzml2isa-galaxy and nmrml2isa-galaxy

**Comment by agbeltran** [comment]
Done. And I see that @althonos is already in the team.

**Pull request merged**
